### ISSUE TITLE
What's license under this repo ?

### ISSUE THREAD

**Issue by hieudoan-ew** [wernerd/ZRTP4PJ#14]
hi @wernerd 

Could you please update the license for this repo? I want to use this code for my purpose. But i did not see the license. 

Hopefully you have time to update the license :) And hope it would be MIT Or Apache :+1:

**Comment by wernerd** [comment]
Every file has it's license header. Because ZRTP may use/include (depending on the configuration) sources from other authors (see the AES code) it's not possible to have a general license.

**Comment by hieudoan-ew** [comment]
@wernerd thank you very much.
