### ISSUE TITLE
hold and call transfer is not working

### ISSUE THREAD

**Issue by drpraveenss** [wernerd/ZRTP4PJ#15]

**Comment by wernerd** [comment]
Some more info available?

Keep in mind that ZRTP is an end-to-end protocol to negotiate encryption keys to setup a secure RTP (SRTP) connection between two endpoints. If you move one endpoint to another device (typically a call transfer) then the not moved endpoint will use the SRTP connection while the receiving endpoint has no idea about this. A 'call transfer' feature needs some way to inform the "not-transferred' endpoint to drop the SRTP context and to re-negotiate the SRTP encryption keys with the new endpoint.

This is inherent to every end-to-end encrypted connection, not only VoIP, if you move one endpoint.

**Comment by drpraveenss** [comment]
Thank you wernerd for this quick reply.
Is there any standard method in ZRTP4PJ (or in PJSIP) to drop the SRTP context and re-negotiate the SRTP encryption.

Although, I have tried following methods to drop the SRTP context and re-negotiate the SRTP keys with the new end point.

//pjmedia_transport_media_stop(zrtp_tp);
         //struct tp_zrtp *zrtp = (struct tp_zrtp*)zrtp_tp;
         //zrtp_DestroyWrapper(zrtp->zrtpCtx);
        // zrtp_tp->op->destroy(zrtp_tp);
         //pjmedia_endpt_destroy(pjsua_get_pjmedia_endpt());
        // pjmedia_transport_stop(zrtp_tp);
        // pjmedia_transport_zrtp_setEnableZrtp 	( zrtp_tp,PJ_FALSE );
        // zrtp_tp->op->
        // pjmedia_transport_close(zrtp_tp);
        //zrtp_tp->op->media_stop(zrtp_tp);
         //zrtp_tp->op->destroy(zrtp_tp);
          //zrtp_tp->op->destroy(zrtp_tp);
         //stop_media_session(ci->id);
        // pjsua_aud_stop_stream(ci->id);
         pjsua_media_channel_deinit(ci->id);// By Praveen

         //if(zrtp_tp)
             	{	// transport_media_stop_custom(	zrtp_tp	);
             	   	// transport_destroy_custom(zrtp_tp);
             	}

The one method 'plsua_media_channel_deinit(ci->id)' seems to works but not properly.

**Comment by drpraveenss** [comment]
One more thing
What is mechanism to properly clean up and stop zrtp session in ZRTP4PJ ???
