### ISSUE TITLE
Compile to android with sqlite

### ISSUE THREAD

**Issue by jresende** [wernerd/ZRTP4PJ#16]
I'm using this in a project with pjsip, and I whant to change the zid file to the database(sqlite) and I would like to know how to do that because I change the Makefile to:
`zrtpobj = zrtp/zrtp/ZrtpCallbackWrapper.o \
    zrtp/zrtp/ZIDCacheDb.o \
    zrtp/zrtp/ZIDRecordDb.o \`

but compiling the pjsip project gives me one error :

> ../../zsrtp/zrtp/zrtp/libzrtpcpp/ZIDCacheDb.h:66: error: undefined reference to 'getDbCacheOps'

how can I solve this problem?

**Comment by wernerd** [comment]
You also need to add the zrtpCacheSqliteBackend file. This implements the necessary funtions for SQlite.

**Comment by jresende** [comment]
It solve the problem. thank you.
But I get the following error in pjproject when I run the make:

```
error: undefined reference to 'base64_encode_block'
error: undefined reference to 'base64_encode_blockend'
error: undefined reference to 'base64_init_decodestate'
error: undefined reference to 'base64_decode_block'
```
zrtpCacheSqliteBackend.c do you have some ideia how to solve this?

**Comment by wernerd** [comment]
I forgot that SQLite requires B64 encoding. The ZRTP source contain two modules
- zrtpB64Encode.c
- zrtpB64Decode.c

which contain the B64 functions. Just add these as well.


Werner


Am 04.03.2016 um 16:52 schrieb jresende:
> It solve the problem. thank you.
> But I get the following error in pjproject when I run the make:
> 
> |error: undefined reference to 'base64_encode_block' error: undefined reference to 'base64_encode_blockend' error: undefined reference to 'base64_init_decodestate' error: undefined reference to 'base64_decode_block' |
> 
> zrtpCacheSqliteBackend.c do you have some ideia how to solve this?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/wernerd/ZRTP4PJ/issues/16#issuecomment-192331233>.
> 

-- 
Werner Dittmann
email: Werner.Dittmann@t-online.de
cell:  +49 173 44 37 659
PGP key: 82EF5E8B

**Comment by jresende** [comment]
I don't have to change something when initialize the média channel? I
compile everything but it still uses the simple.zid file... Not the database
Em 04/03/2016 19:55, "wernerd" <notifications@github.com> escreveu:
