### ISSUE TITLE
after the callback zrtp_signSAS

### ISSUE THREAD

**Issue by jresende** [wernerd/ZRTP4PJ#17]
What should I do when I receive the "zrtp_signSAS" callback?
because the zrtp_showSAS always give me the verified as 0.

I'm speaking of the zrtp_UserCallbacks.

**Comment by jresende** [comment]
@wernerd can you help me on this point? I would like to add a patch to this if it helps

**Comment by wernerd** [comment]
I don't see a patch. Attached a PDF that shows the call flow
when using SAS signatures.

Actually the SAS signature handling does not requires the SAS being
verified, it's meant as a _replacment_ of the user driven SAS
verification. RFC 6189 chapter 7.2 clearly states this.


Wermer

Am 15.03.2016 um 16:51 schrieb jresende:
> @wernerd <https://github.com/wernerd> can you help me on this point? I would like to add a patch to this if it helps
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/wernerd/ZRTP4PJ/issues/17#issuecomment-196891528
> 

-- 
Werner Dittmann
email: Werner.Dittmann@t-online.de
cell:  +49 173 44 37 659
PGP key: 82EF5E8B

**Comment by jresende** [comment]
but if I whant that the user answer check the SAS and based on that I store the information or not. how can I make that? is that implement to this callback? how should I start with that?

Thanks for the reply
jresende

**Comment by wernerd** [comment]
This is the SASVerified() funtion in ZRtp.cpp - see according documentation of that
module. You don't need the sign SAS feature if you implement a UI to display the SAS
and have the users verify it.


Werner

Am 16.03.2016 um 19:10 schrieb jresende:
> but if I whant that the user answer check the SAS and based on that I store the information or not. how can I make that? is that implement to this callback? how should I start with that?
> 
> Thanks for the reply
> jresende
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/wernerd/ZRTP4PJ/issues/17#issuecomment-197462970>
> 

-- 
Werner Dittmann
email: Werner.Dittmann@t-online.de
cell:  +49 173 44 37 659
PGP key: 82EF5E8B

**Comment by jresende** [comment]
where can I find that documentation?
But when should I call that function? in which function should I call? because I have to use zrtp_UserCallbacks to pass the information to the user. But I don't get how to make the information flow from the stack to the user and the answer from the user back to the stack.

**Comment by wernerd** [comment]
The doc is in the source code, header file to be precise. There is a
doc directory and you can generate a fully browsable documentation
using the well known and 'doxygen' command, thus:

cd doc
doxygen Doximini

This should be well known to developers who use open source software.
The callback are similar to other callback of UI systems, e.g if an event
happens then the ZRTP stack uses the callback to inform the UI part.

I have now idea how you designed your UI implementation.


Werner

Am 17.03.2016 um 22:58 schrieb jresende:
> where can I find that documentation? But when should I call that
> function? in which function should I call? because I have to use
> zrtp_UserCallbacks to pass the information to the user. But I don't
> get how to make the information flow from the stack to the user and
> the answer from the user back to the stack.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/wernerd/ZRTP4PJ/issues/17#issuecomment-198101424>
> 

-- 
Werner Dittmann
email: Werner.Dittmann@t-online.de
cell:  +49 173 44 37 659
PGP key: 82EF5E8B
